# Generated by Django 2.0.8 on 2020-04-21 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20200326_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='time_out',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 13, 46, 44, 600624)),
        ),
    ]
